# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f6415df01e700a97e666a2adbb11f3123342670241612039da6df989d3d32086a581c6e44e37909318ccdb2fd248b5933429891dca4c874950e060bfa352ed9c

test:
  secret_key_base: a30f089bae68e704103a92037c54c31b4cd0163698f3b3c57fa3040aa1773edd10da830a60f2df03bb371910cfd152d05e46a6ccbf6e07a76699c377188f7226

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
